/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#54faed",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#154f4a",
        "on-tertiary-fixed": "#2c1700",
        "surface-tint": "#24ddd1",
        "primary-container": "#00d4c8",
        "on-tertiary-fixed-variant": "#683d00",
        "primary-fixed-dim": "#24ddd1",
        "surface-container-low": "#1c1b1b",
        "surface": "#131313",
        "secondary": "#9ad1ca",
        "background": "#131313",
        "surface-container-highest": "#353534",
        "on-secondary": "#003733",
        "secondary-container": "#154f4a",
        "tertiary-container": "#ffac4c",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-container": "#704200",
        "on-tertiary": "#492900",
        "outline": "#849491",
        "inverse-primary": "#006a64",
        "error-container": "#93000a",
        "surface-dim": "#131313",
        "surface-container-high": "#2a2a2a",
        "surface-bright": "#393939",
        "tertiary-fixed-dim": "#ffb86c",
        "on-primary-container": "#005651",
        "inverse-on-surface": "#313030",
        "tertiary": "#ffd1a5",
        "secondary-fixed-dim": "#9ad1ca",
        "on-primary-fixed": "#00201e",
        "on-primary": "#003733",
        "on-primary-fixed-variant": "#00504b",
        "surface-container-lowest": "#0e0e0e",
        "on-background": "#e5e2e1",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#00201e",
        "surface-variant": "#353534",
        "on-secondary-container": "#89bfb9",
        "primary": "#47f1e4",
        "surface-container": "#201f1f",
        "secondary-fixed": "#b6ede6",
        "tertiary-fixed": "#ffdcbc",
        "on-surface-variant": "#bacac7",
        "outline-variant": "#3b4a48",
        "on-surface": "#e5e2e1",
        "on-error": "#690005"
      },
      fontFamily: {
        'manrope': ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
